### ISSUE TITLE
Commit Hooks

### ISSUE THREAD

**Issue by andymikulski** [mozilla/delivery-console#12]
The [Prettier docs](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged) note that setting up post-commit linting is trivial to implement via [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged). I'd be interested to discuss the affordance provided by using these commit hooks, especially with a tool like Prettier which prefers to autofix linting errors.

It's not impossible to set up a workflow where the lint-correcting is near transparent to the developer, but the question is if this is desirable?

**Comment by magopian** [comment]
I'll bring @glasserc in the mix, as we've discussed that quite often already. I believe the TL:DR; is that we'd rather not auto-fix anything for the developer, without them even knowing/noticing it.

Another solution could maybe be having a pre-commit hook that prevents commiting (or pushing) whenever there's a lint error. One can still override that and commit/push, but at least it'll be knowingly and not by mistake. However, I've been told in the past that this is a real pain for some developers, and might go against our goal of "making contributions as easy and affordable as possible".

If I had to state my preference, I'd say -0 on having any kind of hooks, and would only rely on the CI.

**Comment by glasserc** [comment]
I don't object to having hooks that essentially inform the developer that their code won't pass CI. So if you have a check formatting step as part of your CI, then it's OK to have a hook that either corrects the code to match the style guide, or to reject the commit because the code doesn't match the style guide. (If you don't have a check formatting step as part of your CI, then you don't really have a house style and you should take care never to complain about style during PRs.) Of course, remember that all hooks are advisory and can be skipped by the developer (using `git commit --no-verify` etc.), so the value of these hooks is merely that they provide early feedback to the developer.

There's a specific caveat here which is that you shouldn't use husky and lint-staged because they're broken in the presence of partially-staged files, at least until https://github.com/okonet/lint-staged/issues/62 is fixed. See https://github.com/Kinto/kinto-admin/issues/419. I've used `pre-commit` and liked it. I think @mythmon prefers [therapist](http://therapist.readthedocs.io/en/latest/).

**Comment by mythmon** [comment]
I used therapist on mozilla/mozjexl, and [it worked well](https://github.com/mozilla/mozjexl/blob/master/.therapist.yml) to implement both "reject the commit" style checking (eslint) and "correct the code" style checking (prettier) using it.

**Comment by peterbe** [comment]
My JS life has totally changed ever since I changed my Atom to auto-prettier on save. It hurts so much now to go back to Python coding when I have depend on lint warnings. 

Instead of messing with git hooks I'd much prefer to explain the importance and how-to for setting up auto-Prettier-on-save.

**Comment by magopian** [comment]
@rehandalal just advised me against using therapist (that he implemented) because it would add a python dependency, which might not be worth it in a javascript project. I'll thus investigate using `pre-commit`

**Comment by glasserc** [comment]
Just a note that I think you used a different pre-commit from the [one I was talking about](https://pre-commit.com/).

**Comment by magopian** [comment]
oh, but this is a python lib, i'm not sure I want to add python dependencies to this javascript only project :/

**Comment by magopian** [comment]
Let's see how people are reacting to this one ;)
