### ISSUE TITLE
Development requires Normandy backend

### ISSUE THREAD

**Issue by andymikulski** [mozilla/delivery-console#131]
Currently, in order to connect `delivery-console` with the `normandy` API, devs need to clone and spin up instances of both (~along with altering some `console` code that points at the API~). Ideally, devs should _not_ need to manually spin up a local normandy server in order to gain full functionality.

This also is an issue when deploying to dev/stage - currently, the API util does _not_ point to an actual instance of Normandy, which means that even if Auth0 works and users can log into those environments, the recipe/extension APIs will not return data as expected.

I think ideally we want to work with Normandy in a docker container that devs can mount when working locally, but I could be wrong. I think @rehandalal has thoughts on this.

**Comment by mostlygeek** [comment]
A few things here: 

Making dev easier.  Using `docker compose` might make sense to give a pre-configured normandy recipe-server and kinto (remote-settings) back end to test with.   This would take some work but it's a nice way to develop since you're only dependent on localhost. 

stage/prod: 

When deployed to the staging or production environments we should work with ops so delivery-console.stage.mozaws.net and delivery-console.prod.mozaws.net automatically point at the right things.  

What is the best practice for baking in environment configurations for SPAs?

**Comment by peterbe** [comment]
-1 on this. 

It would be great if starting Normandy was easier, but it is what it is. We could make improvements to Normandy so that you don't need to follow a [massive list of commands you have to run](http://normandy.readthedocs.io/en/latest/dev/install.html) but that's going to cost time and energy. 

I think the best solution, in terms of Delivery Console, is to make it possible to point your SPA (on localhost:3000) to the Dev server(s) if you don't want to run Normandy on localhost:8000. 

We'll soon have the same challenge with Remote Settings backend. Now you need another server started in a third terminal. 

I'm not against making it easier to spin up Normandy and Remote Settings but those things belong in those projects.

**Comment by magopian** [comment]
I'm a big +1 on pointing by default to dev servers.

**Comment by peterbe** [comment]
A bit of a cross-post but check out: https://github.com/mozilla/delivery-console/issues/349#issuecomment-412610592
I think that'll potentially making running Normandy so much easier that *this* issue becomes a non-issue.
