### ISSUE TITLE
Webpack is behaving strangely

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#195]
Our webpack builds appear to be doing weird things and it is hard to debug due to create react app.

I'm also not loving this react-app-rewired setup and so I think we should:
- Remove react-app-rewired
- Eject and configure as neccessary

**Comment by peterbe** [comment]
Why do we need react-app-rewired? There's no flow any more.

**Comment by peterbe** [comment]
Was https://github.com/mozilla/delivery-console/pull/196 the only problem or are there still "strange" things? I for one haven't seen any locally.

**Comment by rehandalal** [comment]
I think for now that was it. But #196 didn't fix the problem it just worked around it. I don't want to close this issue but I will downgrade it from a P1.

**Comment by magopian** [comment]
I'm curious, why eject? What are the benefits other than "no need for react-app-rewired"?

I believe CRA is more of a platform than simply a boilerplate, with the tooling that goes with it, and is well "integrated". On previous projects, I've always worked to keep CRA and not eject, because I wanted to deal with the less configuration possible, and benefit from updates.

Also CRA is a well established and known platform for React, and as such might be more approachable to (external or future internal) contributors.

**Comment by rehandalal** [comment]
I think CRA has some sensible defaults for small projects and people who want to get up and running with React quickly but as soon as you need to start tweaking the config ejecting is really the only reasonable option. 

One of the big changes we need to make is stopping the inline style tags that get injected in local development and this is a substantial change to the dev config that is hard to do without ejecting. This change is required to accommodate implementing CSP locally.

Additionally I discovered the build size drops from ~1.2M to ~300k once you eject and strip out the react native stuff that we don't need. That is a significant improvement.

I also don't believe CRA gives us any additional benefit as a platform, over an ejected version of CRA. We're still keeping a lot of the features, just tweaking how they are configured.

**Comment by peterbe** [comment]
> stopping the inline style tags that get injected in local development

What's wrong with those? I'm guessing it's related to Ant but I don't know. 

> strip out the react native stuff 

Which react native stuff?
I generated a build from before my vacation and ran `source-map-explorer` on it. The previous total was 1.27MB and the new total was 1.19MB and most likely the diff is related to dropping `moment.js` in favor of `date-fns`.

**Comment by mythmon** [comment]
>> stopping the inline style tags that get injected in local development

> What's wrong with those? I'm guessing it's related to Ant but I don't know.

Inline styles aren't allowed by our CSP policy.

The react native stuff was a misunderstanding. It stemmed from comparing the output of `yarn build`, which reports size after gzip, and the size reported by the network devtools which was not being gzipped (this has been fixed). The actual difference is minimal, and react native doesn't have a large impact.

**Comment by peterbe** [comment]
CSP policy and react dev server are surely not related. Are the CSP headers sent when you run the dev server (i.e. localhost:3000)?

I know libraries like chart.js injects CSS with inline styles in run-time and that sucks. But it's unrelated to using CRA or not. 

> I also don't believe CRA gives us any additional benefit as a platform 

This I have an issue with. CRA gives us a lot of confidence and free maintenance. It's used and tested by (possibly) thousands of projects. When they upgraded to Webpack 4, all I had to do was `yarn upgrade react-utils --latest` and it worked flawlessly. Now we have to own all that maintenance ourselves :(

I think this makes the project more complicated. Akin to compiling your own kernel vs. just installing Ubuntu. Perhaps we welcome the complexity and it's beyond my decision but I'd like to register that I think the benefits of keeping things simple have been neglected.

**Comment by mythmon** [comment]
> CSP policy and react dev server are surely not related. Are the CSP headers sent when you run the dev server (i.e. localhost:3000)?
>
> I know libraries like chart.js injects CSS with inline styles in run-time and that sucks. But it's unrelated to using CRA or not.

We're talking about injecting inline styles and CSP here because it was something that was difficult to fix (or to reason about) while we were using CRA. Additionally, we wanted to impose our CSP policies both in prod and also in the react dev server. This way we catch CSP problems in development instead of prod. This was also difficult to impossible to do with CRA, since we can't manipulate the Webpack configs directly.

As for whether or not CRA provides benefit or not, I think that CRA doesn't provide *enough* of a benefit *for delivery console*. For my side projects, I'm using CRA whenever I do react apps. In my opinion, the moment we introduced `react-app-rewired` to manipulate the build config, we had gone beyond the limits of where CRA was more help than not. For something like DC, we have very specific requirements for our build system, and the time to maintain it.

As a concrete example, there was a unsoundness bug that we believe was webpack related (#195 / #196). At the time, we couldn't update webpack to pick up the fix to that bug, because we were bound to whatever CRA had.

If we are happy to accept whatever CRA provides, then we should use CRA. For delivery console, I don't think we are happy to accept what CRA provides, and we have demonstrated that we want to go beyond that. I think that trying to keep CRA without accepting what it provides is going to be much more painful than simply maintaining our own build system.
