### ISSUE TITLE
First requests after page load don't wait for authentication

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#248]
When first visiting a page like `/recipe/`, the request to Normandy is made immediately before authorization is available. This means that the first request doesn't have a bearer token at all, which works fine.

Then, if I click a link, the next GET request is made with a bearer token. Currently, my bearer token is stale. Since #233 hasn't landed yet, my token will stay stale until I log out manually and log back in. The effect of this is that initial page loads work, but `pushState`-style navigation doesn't work.

Additionally, when I get a 401 for recipes on the listing page (and in other places), I just get a blank "No data" instead of an error message. That's not great either.

**Comment by peterbe** [comment]
It's tricky. I switched to my branch in https://github.com/mozilla/delivery-console/pull/233 and opened `:3000` for the first time today. Since I haven't used the site in 10+h my accessToken and `expiresAt` will have expired and thus, upon `componentDidMount`, the `webAuth.checkSession()` kicks in. Since `webAuth.checkSession()` works almost the same as `webAuth.authorize()` it basically logged in me in. It didn't really refresh my access token.

**Comment by peterbe** [comment]
For the record, see this comment: https://github.com/mozilla/delivery-console/pull/233#issuecomment-400689741

There might be a "racey condition" that triggers that a stale access token is used in XHR. Well, pretty sure there is. But we can handle it gracefully with the silent authentication.

**Comment by peterbe** [comment]
I made some fixes to https://github.com/mozilla/delivery-console/pull/233 so that the accessToken from localStorage doesn't immediately get used if it has expired. The silent authentication can fix it, if it has expired. 

However, I still need to check what comes first, the first XHR request or the silent authentication.

**Comment by rehandalal** [comment]
I think by connecting the other query components to `accessToken` we can ensure that they retry the request if it fails due to authentication.
