### ISSUE TITLE
Authentication error: Login Required

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#262]
I occasionally get the following error message:

![image](https://user-images.githubusercontent.com/987136/42195134-6ed15bb6-7e45-11e8-9735-2ad2870eaa07.png)

I haven't figured out STR yet.

**Comment by rehandalal** [comment]
From auth0-js:
> checkSession(options, callback): Allows you to acquire a new token from Auth0 for a user who already has an SSO session established against Auth0 for your domain. If the user is not authenticated, the authentication result will be empty and you'll receive an error like this: {error: 'login_required'}.The method accepts any valid OAuth2 parameters that would normally be sent to /authorize. Everything happens inside an iframe, so it will not reload your application or redirect away from it.

**Comment by peterbe** [comment]
That's funny because I got the same error 2 min ago on my side-project that uses a very similar approach as delivery-console. 

So basically, it means that Auth0 wants you to explicitly visit the login screen again. So if we get `err.login_required` in the error callback handler of `checkSession` we simply consider the user as logged out and the user has to explicitly log in again.

The strange thing is, on my side-project, when this happened, I had to click the "Log in" button again but it totally recognized me in the Auth0 UI. All I had to do was to click to confirm that that was the email I used last time.
