### ISSUE TITLE
Help contributors set up their environment

### ISSUE THREAD

**Issue by magopian** [mozilla/delivery-console#349]
At the moment there's no help other than [some contributing notes](https://github.com/mozilla/delivery-console/blob/master/CONTRIBUTING.md#setting-up-a-pre-commit-hook) that explains how to set up the environment and tools we use.

In the [kinto project](https://github.com/Kinto/kinto/blob/master/Makefile#L38) we have a [detailed documentation](https://kinto.readthedocs.io/en/latest/community.html#how-to-contribute) and a [Makefile entry](https://github.com/Kinto/kinto/blob/master/Makefile#L38) that sets everything up automatically.

Maybe we could have something similar here, or a `setup` script entry in the `package.json`? The

**Comment by peterbe** [comment]
One thing that I think will help is to make it easier to run Normandy. 
We have some [pending changes](https://github.com/mozilla/normandy/pull/1435) that uses `docker-compose` in CircleCI. `docker-compose` is very convenient and lots of people have Docker installed. If we can extract, from the Circle config, the one single command you need to start up a complete Normandy with one command I think that would help Delivery Console. You'd probably always need to run it in a separate terminal but typing `docker-compose up web` after a git clone would be a *lot* easier than having to read [the dev docs](http://normandy.readthedocs.io/en/latest/dev/install.html). Also, whatever that `docker-compose` command becomes we should make it resilient so that it takes care of things like downloading geo databases and updating actions etc in an idempotent way.

**Comment by jaredkerim** [comment]
Soon we will have a Makefile for standing up the full delivery intake stack (Experimenter, Delivery Console, Normandy) so that will take over for this.
