### ISSUE TITLE
Circle CI implementation

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#4]
We should get Circle CI up and running on it's 2.0 API.

It should be able to:
- [x] Run tests
- [x] Lint the code
- [x] Build the project
- [ ] Get a first green build (ignoring deployment)

**Comment by peterbe** [comment]
[A decent start is in place](https://github.com/mozilla/delivery-console/blob/master/.circleci/config.yml)

Right now it's [failing](https://circleci.com/gh/mozilla/delivery-console/5) because the tests don't even run locally yet. 

Also, the code contains code warnings so we can expect the CI to break on that too since `yarn run build` will break if `CI=true` which I expect it to be. 

Note that if the tests pass (including making the `build`) it will execute [`bin/deploy.sh`](https://github.com/mozilla/delivery-console/blob/master/bin/deploy.sh) if it's a `master` build or a git tag. That script doesn't do anything. That's where https://bugzilla.mozilla.org/show_bug.cgi?id=1442345 comes in. 

For now, once the tests and build works and we get our first green Circle CI build, let's close this issue. The deployment discussion will move over to https://github.com/mozilla/delivery-console/issues/5

**Comment by peterbe** [comment]
@andymikulski Over to you. Once you've got a `yarn run test` and `CI=true yarn run build` working locally, you can close this issue.
