### ISSUE TITLE
Make publish button stand out

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#52]
Copied from: https://github.com/mozilla/normandy/issues/1033

> @MattGrimes had some trouble finding the publish button in the new UI until I pointed it out to him. I think there's two minor improvements we could make here:
> 
> After approving a revision, users have to go back to the recipe details page to publish the recipe, although publishing immediately after reviewing is a common user flow. Maybe we should redirect users back to that page after approving a review? Or maybe the review page should show a publish button if the recipe is eligible to be published?
> 
> On the recipe details page, the publish button blends in with the edit/clone buttons a bit too well. Maybe we should relocate it, or maybe make it green?

**Comment by peterbe** [comment]
@rehandalal Do you think we can close this now?
In https://github.com/mozilla/delivery-console/issues/284 we made the notification message a bunch better and we made it so that you're redirected back to the page that *has* the Publish button after you approve. 

Ant doesn't have the concept of different colored buttons. We could easily hack it by doing something like `style={{backgroundColor: GREEN}}` but it stinks because it'd be the *only* button that isn't in the consistent scheme of colors.
