### ISSUE TITLE
"Enabled" and "Enrollment active" columns are duplicate information

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#573]
The "Enrollment active" column shows the same information as "Enabled", plus more. We should remove the enabled column and make the enrollment active column better, such as #572.

![image](https://user-images.githubusercontent.com/305049/48278657-04b7f680-e403-11e8-93e1-60f4c5f0e45f.png)

**Comment by peterbe** [comment]
Note-to-self; We can't easily tackle this issue yet. In https://github.com/mozilla/delivery-console/pull/684 we, slightly, improve the "Enrollment active" column to emphasize recipes that are approved and needs the action to enable it. 

Ideally, this last column should be called "Status" (or something) instead and inside it it should have a very descriptive state. E.g. "Active", "Paused", "Approved not enabled", "Approval rejected", "Approval requested", and "Draft". 

And the reason why we can't easily tackle this yet is because we don't have the full approval process information for each recipe on the listing page. Also, we're in the midst of moving from the v2 to the v3 API which might complicate the effort.
