### ISSUE TITLE
Stable sample filter UI should support fractional sample rates

### ISSUE THREAD

**Issue by mythmon** [mozilla/delivery-console#585]
In the stable sample filter object, the current UI restricts the sample to integer percentages. It is common to want to use sample rates as low 0.1%. Bucket sample can be used for this (since it gives control over the denominator), but it would be good for stable sample to also support fractional percentages.

**Comment by peterbe** [comment]
I noticed an unrelated/related bug. I wanted to see what happens when I typed in "0.2" in there when editing a recipe with stable sample filter object. The in-widget validation removed by an attempt to type something non-integer and the input was changed to just "%". I just pressed the Save button. Here's what happened...

In the server the rate was set to:

```python
[{'countries': ['SE', 'DK'], 'type': 'country'},
 {'channels': ['nightly'], 'type': 'channel'},
 {'versions': [66], 'type': 'version'},
 {'input': ['"something"', 'normandy.recipe.id'],
  'rate': 0.002,
  'type': 'stableSample'}]
```

Which is what I typed!

In the recipe details page I now see this:

<img width="407" alt="screen shot 2019-01-04 at 2 09 36 pm" src="https://user-images.githubusercontent.com/26739/50705958-6c1cac00-102a-11e9-9fe5-dc811d1c9ee3.png">

...which isn't right. 

And when I click back to edit it again it looks like this:

<img width="704" alt="screen shot 2019-01-04 at 2 10 21 pm" src="https://user-images.githubusercontent.com/26739/50705998-835b9980-102a-11e9-975c-916c82373e97.png">
