### ISSUE TITLE
Recipe filters get dropped automatically during editing

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/delivery-console#598]
Ran into this issue when I was editing [this recipe](https://delivery-console.prod.mozaws.net/recipe/636/) in order to bump the user sample size from 10% to 100%.

After successfully updating the sample size, and saved the change in the recipe edit dashboard, the original geo filter got dropped. Had to file another edition to add the geo filter back in. Note that there was only one item in the geo filter in this recipe, not sure if it would drop all the geo filters, or just part of it.

**Comment by mythmon** [comment]
[Testing on dev](https://delivery-console.dev.mozaws.net/recipe/133) I was able to reproduce this with locale and channel as well, but not version. Additionally, I verified that the problem is not what is coming from the Normandy server: the responses coming from the server have the expected data, and the first wrong data is in the PATCH request to edit the recipe.

Not sure if it is related, but I saw this while testing. Notice that although there are geo and locale filters, the tab counter says 0.

![image](https://user-images.githubusercontent.com/305049/48733597-eff41380-ebf7-11e8-862f-db8f4dc813f7.png)

**Comment by mythmon** [comment]
**STR**

1. Create and save a recipe including both a sampling filter and at least one filter of country, locale, or channel.
2. Edit the recipe, changing only the sample rate (I used a bucket sample and increased the count from 5 to 50).

**Expected**
The recipe should only have its sample rate changed, and nothing else.

**Observed**
The recipe's other filters are removed (and the sample rate is changed).

**Comment by rayborn** [comment]
I had a field dropped cloning from 641 to 642 then again when I cloned 642 to 643.  This occured even when I wasn't switching panes.

**Comment by peterbe** [comment]
Note-to-self; The STRs didn't work for me. However, what happened to me was that I was watching the recipe (aka. the details page) and I could see it has a stable sampling and a country. I clicked "Edit" and now suddenly the "Geo" tab suddenly said "Geo (0)" when it used to say "Geo (1)" before. Either way, opening that tab it has indeed wiped my previous Country selection that used to be there. And if I touch nothing other than the Save button, it indeed removes my previous Country selection from the database.

**Comment by peterbe** [comment]
Another thing I've noticed is that the edit page remembers which tab (Sampling, Browser, or Geo) you were on last time. It uses `window.sessionStorage`. If you go the Edit page with that `sessionStorage` point to "Geo" it works. If not, the Geo tab data is "lost".

**Comment by peterbe** [comment]
Please unsubscribe, if you want to, as I use this as a place to jot down notes about this bug. 

Basically, we're doing this:

```jsx
<form onSubmit={event => {
  event.preventDefault()

  // Use your imagination...
  sendFormData({country: event.form.values.country.value})
  // This will send the "initialValueFromServer" or whatever the user overwrote it to.
  // ...If, and only if, it was displayed. 


}}>
  {/* imagine this being Antd components... */}
  {displayCountryInput && <input name="country" value={initialValueFromServer}>}
</form>
```

Basically, we're putting the previous server data into the form, and whatever is submitted is the total new data we send to the server. 

If the Country (for example) input is never displayed it's not entered into any form so it won't ever be part of the data we send to the server on the next save. 
Because, on the server we assume that what's being sent is the complete filter object. If anything was omitted (e.g. you used to have `channels=1,2,3` but now it's not included at all) the server will assume the user has selected to delete the `channels` filter object entirely.

**Comment by mythmon** [comment]
@rayborn @ncloudioj to summarize what @peterbe found in the previous comment, for now to work around the bug visit each of the filter tabs before saving any recipe.
