### ISSUE TITLE
Option for VPN to not block site contents on a local instance

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/delivery-console#890]
The VPN needs to be connected for certain fields to show on a local development instance. There should be a way that a user can view all the fields without needing to connect the to the VPN.

Not sure if this needs a normandy change as well.

**Comment by rehandalal** [comment]
VPN is not required locally. If you are seeing `VPN Disconnected` locally this is because Delivery Console is unable to reach the configured instance of Normandy. This is configured through `REACT_APP_NORMANDY_ADMIN_API_ROOT_URL` in your `.env` file and if unset will default to `https://localhost:8000/api/`.

If you are using a local instance of Normandy please also make sure to navigate to your local instance in the browser once and add an exception for the security certificate or run Normandy with SSL disabled and change the URL to `http://` in your DC `.env` file.

**Comment by jrbenny35** [comment]
@rehandalal thanks! I definitely missed the step regarding that ENV variable. That was it!
