### ISSUE TITLE
Write up some contribution guidelines

### ISSUE THREAD

**Issue by rehandalal** [mozilla/delivery-console#9]
We should come up with some general guidelines for contributing to the project and as @peterbe called it a manifesto that covers some things like why we chose certain tech and how to structure files etc.

**Comment by peterbe** [comment]
Some (good) opinions:

* Unit tests should concern itself with "public APIs" as much as possible.
* Prettier all the code with default configuration.
* Avoid global CSS that isn't tied to a specific component.
* Run lint check and all tests locally before making a pull request.
* Submit pull requests from branches on *your* fork.
* Don't assume that network calls always work. Check for and deal with failing network calls beyond `console.error`.
* camelCase all the things (except class names) and camelCase acronyms. I.e. `myUrl` instead of `myURL`.
* Favor simple over complex.
* All comments should explain **why**, never *what*. 
* Favor conformity and consistency instead of personal preference.

**Comment by magopian** [comment]
Do we want to add a note on documentation? Maybe state that any contribution to the API should be thoroughly documented (following some template)?

Also maybe some more generic things like
- you are not your code
- be kind
- tell us before tackling a big issues
- ask us before adding a new feature or changing a big part of the code
- we don't accept PR that change the formatting (adding or removing all the semicolons for example)
- ...

**Comment by peterbe** [comment]
* Every new developer feature should come with documentation. E.g. "How to run lint checking". New tools and tricks that comes in without documentation is a fail.

**Comment by peterbe** [comment]
* Push feature branches to your own fork and make pull requests from there to `mozilla`.
