### ISSUE TITLE
Uploading an invalid extension doesn't properly report the server-provided error message

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/delivery-console#942]
**[Affected versions]:**
- Firefox Release 67.0.3, Build ID 20190618025334
- Firefox Beta 68.0b11, Build ID 20190617172838
- Firefox Nightly 69.0a1, Build ID 20190613215335

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Access to NORMANDY Delivery Console https://delivery-console.stage.mozaws.net/ is needed.

**[Steps to reproduce]:**
1. Start the browser and navigate to https://delivery-console.stage.mozaws.net/extension/new/.
2. Upload a signed xpi.
3. Write a valid name in the "Name" field.
4. Click save and observe the behavior.

**[Expected results]:**
- The extension is saved/uploaded to the server.

**[Actual results]:**
- The `Extension cannot be saved. Please correct the form items highlighted below.` error message is displayed, no fields are highlighted and the extension is not saved/uploaded.

**[Notes]:**
- Not sure if this is related to #938 or if this should be in the mozilla/normandy repo, but the action is different enough that this should be tracked separately. 
- Attached a screen shot of the issue.

![image](https://user-images.githubusercontent.com/18304511/60022339-4ba9e200-969c-11e9-8739-65f263a31a94.png)

- Attached a screenshot of the Browser console errors:

![console-output-when-saving-an-uploaded-extension](https://user-images.githubusercontent.com/18304511/60022496-9fb4c680-969c-11e9-9f4e-09448a8552bb.png)

**Comment by mythmon** [comment]
I can't reproduce this. Can you share a copy of the add-on that you used with me?

**Comment by SoftVision-CosminMuntean** [comment]
@mythmon Ciprian is in PTO this week, but I can share with you the used add-on. 
You can download it from [here](https://drive.google.com/open?id=19TRSwSvXmcb3fkSjdvXgBMid34Cpi7af). Please let me know if you need more information.

**Comment by mythmon** [comment]
The error returned by the server is `{"xpi":"Web extensions must have a manifest key \"applications.gecko.id\"."}`. The extension is not valid for use on Normandy. The UI should present the error message, but the underlying problem is the extension. Using a compatible add-on should help.

Also, in the future, the headers of responses, especially when the entire payload isn't available, aren't very useful. They "Response" tab is often more useful. The most useful thing however would be to right click on any request and click "Copy all as HAR" and attach that file. It includes all the relevant details.
